title: H! This is My Blog..
author: Luca
email: daiveedlucas049@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  I'm a final year student of Computer Science, lover of open source technology and a big fan of being a big fan of new technologies

# social links
twitter_username: https://www.twitter.com/lucadavid075 # DO NOT include the @ character, or else the build will fail!
github_username:   https://www.github.com/lucadavid075 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
